---
dependency:
  name: galaxy
driver:
  name: azure
lint:
  name: yamllint
platforms:
  - name: my-role-bionic
    resource_group_name: infracode_sandbox
    vm_size: Standard_B1s
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 18.04-LTS
      version: latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  log: True
  options:
    become: True
scenario:
  name: default
verifier:
  name: testinfra
  options:
    sudo: True
  lint:
    name: flake8
